/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsString, IsEnum, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { EnumNewsSource } from "./EnumNewsSource";
import { EnumNewsTanant } from "./EnumNewsTanant";

@ObjectType()
class News {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  description!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  descriptionPreview!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  slug!: string;

  @ApiProperty({
    required: true,
    enum: EnumNewsSource,
  })
  @IsEnum(EnumNewsSource)
  @Field(() => EnumNewsSource, {
    nullable: true,
  })
  source?: "PROTANKI" | "LESTA" | "WARGAMING" | "OTHER";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sourceUrl!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tags!: string | null;

  @ApiProperty({
    required: true,
    enum: EnumNewsTanant,
  })
  @IsEnum(EnumNewsTanant)
  @Field(() => EnumNewsTanant, {
    nullable: true,
  })
  tanant?: "RU" | "Eu" | "ALL";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  title!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { News as News };
